# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Episode

# Model Form Field configuration
form: $/bubblecore/podcast/models/episode/fields.yaml

# Model Class name
modelClass: Bubblecore\Podcast\Models\Episode

# Default redirect location
defaultRedirect: bubblecore/podcast/episodes

# Create page
create:
    title: Create Episode
    redirect: bubblecore/podcast/episodes/update/:id
    redirectClose: bubblecore/podcast/episodes

# Update page
update:
    title: Edit Episode
    redirect: bubblecore/podcast/episodes
    redirectClose: bubblecore/podcast/episodes

# Preview page
preview:
    title: Preview Episode